---
- name: Provision CICS Data sets and start the region
  hosts: all
  gather_facts: false
  environment: "{{ environment_vars }}"

  vars:
    applid: IYK2ZPY1

  tasks:
    - name: Create the auxiliary temporary storage data set (DFHTEMP)
      ibm.ibm_zos_cics.aux_temp_storage:
        state: initial
        region_data_sets:
          dfhtemp:
            dsn: "{{ ansible_user }}.REG.{{ applid }}.DFHTEMP"
          
    - name: Create the auxiliary trace data set (DFHAUXT)
      ibm.ibm_zos_cics.aux_trace:
        state: initial
        region_data_sets:
          dfhauxt:
            dsn: "{{ ansible_user }}.REG.{{ applid }}.DFHAUXT"

    - name: Create the second auxiliary trace data set (DFHBUXT)
      ibm.ibm_zos_cics.aux_trace:
        state: initial
        destination: B
        region_data_sets:
          dfhbuxt:
            dsn: "{{ ansible_user }}.REG.{{ applid }}.DFHBUXT"
          
    - name: Create the transaction dump data set (DFHDMPA)
      ibm.ibm_zos_cics.transaction_dump:
        state: initial
        region_data_sets:
          dfhdmpa:
            dsn: "{{ ansible_user }}.REG.{{ applid }}.DFHDMPA"
          
    - name: Create the second transaction dump data set (DFHDMPB)
      ibm.ibm_zos_cics.transaction_dump:
        state: initial
        destination: B
        region_data_sets:
          dfhdmpb:
            dsn: "{{ ansible_user }}.REG.{{ applid }}.DFHDMPB"
   
    - name: Create the global catalog data set (DFHGCD)
      ibm.ibm_zos_cics.global_catalog:
        state: initial
        cics_data_sets:
          sdfhload: "CTS610.CICS740.SDFHLOAD"
        region_data_sets:
          dfhgcd:
            dsn: "{{ ansible_user }}.REG.{{ applid }}.DFHGCD"
   
    - name: Create the CSD data set (DFHCSD)
      ibm.ibm_zos_cics.csd:
        state: initial
        cics_data_sets:
          sdfhload: "CTS610.CICS740.SDFHLOAD"
        region_data_sets:
          dfhcsd:
            dsn: "{{ ansible_user }}.REG.{{ applid }}.DFHCSD"
   
    - name: Update the CSD data set with the CSDUP script
      ibm.ibm_zos_cics.csd:
        state: changed
        cics_data_sets:
          sdfhload: "CTS610.CICS740.SDFHLOAD"
        region_data_sets:
          dfhcsd:
            dsn: "{{ ansible_user }}.REG.{{ applid }}.DFHCSD"
        input_location: INLINE
        input_content: ADD GROUP(DFHTERMC) LIST(DFHLIST1)

    - name: Create the transient data intrapartition data set (DFHINTRA)
      ibm.ibm_zos_cics.td_intrapartition:
        state: initial
        region_data_sets:
          dfhintra:
            dsn: "{{ ansible_user }}.REG.{{ applid }}.DFHINTRA"
   
    - name: Create the local request queue data set (DFHLRQ)
      ibm.ibm_zos_cics.local_request_queue:
        state: initial
        region_data_sets:
          dfhlrq:
            dsn: "{{ ansible_user }}.REG.{{ applid }}.DFHLRQ"
   
    - name: Create the local catalog data set (DFHLCD)
      ibm.ibm_zos_cics.local_catalog:
        cics_data_sets:
          sdfhload: "CTS610.CICS740.SDFHLOAD"
        state: initial
        region_data_sets:
          dfhlcd:
            dsn: "{{ ansible_user }}.REG.{{ applid }}.DFHLCD"
