---
- name: Provision CICS Data sets and start the region
  hosts: all
  gather_facts: false
  environment: "{{ environment_vars }}"

  vars:
    applid: IYK2ZPY1

  module_defaults:
    group/ibm.ibm_zos_cics.region:
      state: initial
      cics_data_sets:
        sdfhload: "CTS610.CICS740.SDFHLOAD"
      region_data_sets:
        template: "{{ ansible_user }}.REG.{{ applid }}.<< data_set_name >>"

  tasks:
    - name: Create the auxiliary temporary storage data set (DFHTEMP)
      ibm.ibm_zos_cics.aux_temp_storage:
          
    - name: Create the auxiliary trace data set (DFHAUXT)
      ibm.ibm_zos_cics.aux_trace:

    - name: Create the second auxiliary trace data set (DFHBUXT)
      ibm.ibm_zos_cics.aux_trace:
        destination: B
          
    - name: Create the transaction dump data set (DFHDMPA)
      ibm.ibm_zos_cics.transaction_dump:
          
    - name: Create the second transaction dump data set (DFHDMPB)
      ibm.ibm_zos_cics.transaction_dump:
        destination: B
   
    - name: Create the global catalog data set (DFHGCD)
      ibm.ibm_zos_cics.global_catalog:
   
    - name: Create the CSD data set (DFHCSD)
      ibm.ibm_zos_cics.csd:
   
    - name: Update the CSD data set with the CSDUP script
      ibm.ibm_zos_cics.csd:
        state: changed
        input_location: INLINE
        input_content: ADD GROUP(DFHTERMC) LIST(DFHLIST1)

    - name: Create the transient data intrapartition data set (DFHINTRA)
      ibm.ibm_zos_cics.td_intrapartition:
   
    - name: Create the local request queue data set (DFHLRQ)
      ibm.ibm_zos_cics.local_request_queue:
   
    - name: Create the local catalog data set (DFHLCD)
      ibm.ibm_zos_cics.local_catalog:
   